[tool.black]
line-length = 120
target-version = ['py310']
include = '\.pyi?$'
skip-magic-trailing-comma = true

[tool.isort]
known_first_party = ["autotune", "nkigym"]
profile = "black"
line_length = 120